---
- name: add line into file
  lineinfile:
    path: /usr/share/phpmyadmin/config.inc.php
    line: "{{item}}"
    create: yes
  with_items:
    - "{{literal_line}}"
  when: add_config_mysql == "yes"

- block:
  - name: "Checking folders"
    stat:
     path: "{{item}}"
    register: folder_stats
    with_items:
    - ["{{ phpmyadmin_conf_path }}"]
  - name: "Creating multiple folders without disturbing previous permissions"
    file:
     path: "{{item.item}}"
     state: directory
     mode: 0755
     group: root
     owner: root
    when: item.stat.exists == false
    with_items:
    - "{{folder_stats.results}}"
    when: add_config_mysql == "no"
- name : Download the phpmyadmin version {{phpmyadmin_version}}
  get_url:
    url: "https://files.phpmyadmin.net/phpMyAdmin/{{phpmyadmin_version}}/phpMyAdmin-{{phpmyadmin_version}}-english.tar.gz"
    dest: "/tmp/"
  when: add_config_mysql == "no"
- name: Extract archive
  unarchive:
   src: "/tmp/phpMyAdmin-{{phpmyadmin_version}}-english.tar.gz"
   dest: "{{ phpmyadmin_conf_path }}"
   remote_src: yes
   extra_opts: [--strip-components=1]
  when: add_config_mysql == "no"
- name: Ensure phpmyadmin version {{phpmyadmin_version}} is configured.
  template:
    src: config.inc.php
    dest: "{{ phpmyadmin_conf_path }}"
    mode: 0644
  when: add_config_mysql == "no"

#- name:  phpmyadmin nginx is configured.
#  template:
#    src: phpmyadmin.conf
#    dest: "/etc/nginx/conf.d/"
#    mode: 0644
#- name: add server mysql
  #lineinfile:
  #  dest: /usr/share/phpmyadmin/config.inc.php
  #  line: '{{ item }}'
  #  insertbefore: 'add server'
  #with_items: "{{ items_list }}"
  #blockinfile:
  #  path: /usr/share/phpmyadmin/config.inc.php
#    backup: yes
    #insertafter: 'add server'
  #  marker: "/* ------------ */"
#    state: present
#    block: "{{ lookup('file', 'localfile.txt') }}"
#- name:  phpmyadmin nginx is configured.
#  template:
#    src: phpmyadmin.conf
#    dest: "/etc/nginx/conf.d/"
#    mode: 0644
#- name: Add default username and password for MySQL connection.
#  blockinfile:
#    path: /usr/share/phpmyadmin/config.inc.php
#    backup: yes
#    marker: "/* ------------ */"
#    block: |
#      $i++;
#      $cfg['Servers'][$i]['auth_type'] = 'cookie';
#      $cfg['Servers'][$i]['verbose'] = '{{mysql_hostname}}';
#      $cfg['Servers'][$i]['host'] = '{{mysql_host_IP}}';
#      $cfg['Servers'][$i]['compress'] = false;
#      $cfg['Servers'][$i]['AllowNoPassword'] = false;
#  when: add_config_mysql == "yes"
